### ISSUE TITLE
`Bandwidth.SipPeer.createAsync` fails with `Termination hosts are not allowed for new API`

### ISSUE THREAD

**Issue by amiller-gh** [Bandwidth/node-numbers#38]
Despite `terminationHosts` being set in the README example, the API call will fail if the key is provided. Remove from documentation.

**Comment by amiller-gh** [comment]
It also appears that `voiceHosts` and `smsHosts` are optional. Is this accurate?

**Comment by ajrice6713** [comment]
Hey there! 

Thank you for raising that up - I will get a PR open to address the documentation update to remove `terminationHosts` from the example. 

`voiceHosts` and `smsHosts` are optional, I will include a comment on that line to inform.
