### ISSUE TITLE
`numbers.Order.create()` isn't promisified

### ISSUE THREAD

**Issue by colllin** [Bandwidth/node-numbers#4]
When I call `numbers.Order.create(myClient, {myData: 1})`, it returns `undefined`.  If I pass a callback, i.e. `numbers.Order.create(myClient, {myData: 1}, () => console.log('it is calling back'))`, it calls the callback.  I think there's something wrong with the promisification of this function — possibly related to the check in the beginning which makes the client optional?  Or maybe it's not being promisified at all.

**Comment by dtolb** [comment]
@colllin the methods are promisified using the Bluebird "PromisifiyAll" as such each method has a peer like `{methodName}Async`

You'll need to call the `createAsync` method like:

```js
try {
  const myVal = await numbers.Order.createAsync(myClient, data);
  console.log(myVal);
} 
catch (e) {
  console.log('Error when creating an order');
  console.log(e)
}
```

Checkout the lil blurb in the [Readme](https://github.com/Bandwidth/node-numbers#async-methods), apologies if that was not clear 👍
