### ISSUE TITLE
Having issues with Get orders from Site.getOrders(query)

### ISSUE THREAD

**Issue by h36ahmed** [Bandwidth/node-numbers#48]
Hi, I am having issues with Get orders from Site.getOrders(query) because in the code base, the query param is not being read into the request and `page` and `size` are required parameters in `accounts/{accountId}/sites/{siteId}/orders` as per documentation. Could someone in the team fix this asap?

**Comment by ajrice6713** [comment]
Hey @h36ahmed,

Thank you for bringing this to our attention, I can see in that function where query params are accepted but never passed into the preceding `makeRequest` function. We will get this work scoped and push a fix in a bit. I link this issue to the PR that gets opened. 

We release every 2 weeks on tuesdays - so i expect this fix to be implemented in v1.8.1

**Comment by h36ahmed** [comment]
Thank you!

**Comment by ajrice6713** [comment]
Hey @h36ahmed,

The updated package will be published next tuesday.
