### ISSUE TITLE
MoveTns API missing

### ISSUE THREAD

**Issue by h36ahmed** [Bandwidth/node-numbers#50]
Hi Bandwidth Team,

I was trying to implement the following API, account/account-id/moveTns, as shown in screenshot but I realized your SDK does not support it. Could you please let me know if this can implemented in March 1 release as well?

<img width="1555" alt="image" src="https://user-images.githubusercontent.com/13081913/155161536-184b2037-8df9-446d-9148-9215f6150497.png">

**Comment by ajrice6713** [comment]
Hey @h36ahmed - I dont know if we can get this into the March 1 release but its likely we could get it into the March 15th Release.

**Comment by ajrice6713** [comment]
Hey @h36ahmed 

This functionality is included in `v1.9.0`
