### ISSUE TITLE
Don't order multiple number

### ISSUE THREAD

**Issue by klals** [Bandwidth/node-numbers#63]
### Description
I Try to create order with multiple number using this library but i order only one order. 
herer is my sample code snippet:-
var order = {
    name:"A Test Order",
    siteId: selectedSite,
    existingTelephoneNumberOrderType: {
        telephoneNumberList: [
            { telephoneNumber: number },
            { telephoneNumber: number }
          ]
    }
  };

numbers.Order.create(order, function (err, res) {
    if (err) {
      console.log("Error: " + err);      
    } else {
      console.log("Order successfully created");
    }
  });
  
so, please give some suggestion or help to resolve this issue.

**Comment by ajrice6713** [comment]
Hey @klals - looks like you close this issue, do you still need help getting set up with number ordering?

**Comment by klals** [comment]
Hey @ajrice6713,
I resolve above issue but i want to create E911 order using this library but in documentation i didn't found so please help me of sample code.
in bandwidth documentation i check all data pass in xml format but i want to create order using this library

https://dev.bandwidth.com/apis/numbers/#tag/E911/operation/CreateE911Order

**Comment by ckoegel** [comment]
Hi @klals The ability to create an E911 order is not currently supported by this SDK. I've added this to our backlog. For the time being, I'd recommend using axios to make the request, following the example payload shown in the spec. I've provided a code snippet below.
```
const axios = require('axios');
const accountId = 'your account id';

const instance = axios.create({
    baseURL: 'https://dashboard.bandwidth.com/api/v1/',
    timeout: 1000,
    headers: {'Content-Type': 'application/xml'}
});

instance.post(`/accounts/${accountId}/e911s`, `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<E911Order>
  <CustomerOrderId>CustomOrderId1</CustomerOrderId>
  <TelephoneNumbers>
    <TelephoneNumber>9706542332</TelephoneNumber>
    <TelephoneNumber>9706542333</TelephoneNumber>
  </TelephoneNumbers>
  <DeleteTNSpecificE911Address>true</DeleteTNSpecificE911Address>
</E911Order>`);
```
